In [1]:
#Load the dataset
import pandas as pd
import numpy as np
pd.read_csv('C:/Users/varsh/Downloads/data/Hospital General Information.csv', engine = 'python')
df =pd.read_csv ('C:/Users/varsh/Downloads/data/Hospital General Information.csv',engine='python')
df.head(20)


Provider ID                     Hospital Name  \
0         10001  SOUTHEAST ALABAMA MEDICAL CENTER   
1         10005     MARSHALL MEDICAL CENTER SOUTH   
2         10006    ELIZA COFFEE MEMORIAL HOSPITAL   
3         10007          MIZELL MEMORIAL HOSPITAL   
4         10008       CRENSHAW COMMUNITY HOSPITAL   
5         10011                 ST VINCENT'S EAST   
6         10012    DEKALB REGIONAL MEDICAL CENTER   
7         10016     SHELBY BAPTIST MEDICAL CENTER   
8         10018             CALLAHAN EYE HOSPITAL   
9         10019    HELEN KELLER MEMORIAL HOSPITAL   
10        10021               DALE MEDICAL CENTER   
11        10022           CHEROKEE MEDICAL CENTER   
12        10023      BAPTIST MEDICAL CENTER SOUTH   
13        10024     JACKSON HOSPITAL & CLINIC INC   
14        10029       EAST ALABAMA MEDICAL CENTER   
15        10032                  WEDOWEE HOSPITAL   
16        10033    UNIVERSITY OF ALABAMA HOSPITAL   
17        10034            COMMUNITY HOSPITAL INC   
18        10035   CULLMAN REGIONAL MEDICAL CENTER   
19        10036       ANDALUSIA REGIONAL HOSPITAL   

                         Address        City State  ZIP Code County Name  \
0         1108 ROSS CLARK CIRCLE      DOTHAN    AL     36301     HOUSTON   
1     2505 U S HIGHWAY 431 NORTH        BOAZ    AL     35957    MARSHALL   
2             205 MARENGO STREET    FLORENCE    AL     35631  LAUDERDALE   
3                  702 N MAIN ST         OPP    AL     36467   COVINGTON   
4            101 HOSPITAL CIRCLE     LUVERNE    AL     36049    CRENSHAW   
5     50 MEDICAL PARK EAST DRIVE  BIRMINGHAM    AL     35235   JEFFERSON   
6           200 MED CENTER DRIVE  FORT PAYNE    AL     35968     DE KALB   
7        1000 FIRST STREET NORTH   ALABASTER    AL     35007      SHELBY   
8           1720 UNIVERSITY BLVD  BIRMINGHAM    AL     35233   JEFFERSON   
9   1300 SOUTH MONTGOMERY AVENUE   SHEFFIELD    AL     35660     COLBERT   
10              126 HOSPITAL AVE       OZARK    AL     36360        DALE   
11              400 NORTHWOOD DR      CENTRE    AL     35960    CHEROKEE   
12     2105 EAST SOUTH BOULEVARD  MONTGOMERY    AL     36116  MONTGOMERY   
13              1725 PINE STREET  MONTGOMERY    AL     36106  MONTGOMERY   
14        2000 PEPPERELL PARKWAY     OPELIKA    AL     36801         LEE   
15         209 NORTH MAIN STREET     WEDOWEE    AL     36278    RANDOLPH   
16         619 SOUTH 19TH STREET  BIRMINGHAM    AL     35233   JEFFERSON   
17           805 FRIENDSHIP ROAD   TALLASSEE    AL     36078      ELMORE   
18      1912 ALABAMA HIGHWAY 157     CULLMAN    AL     35058     CULLMAN   
19  849 SOUTH THREE NOTCH STREET   ANDALUSIA    AL     36420   COVINGTON   

    Phone Number         Hospital Type  \
0     3347938701  Acute Care Hospitals   
1     2565938310  Acute Care Hospitals   
2     2567688400  Acute Care Hospitals   
3     3344933541  Acute Care Hospitals   
4     3343353374  Acute Care Hospitals   
5     2058383122  Acute Care Hospitals   
6     2568453150  Acute Care Hospitals   
7     2056208100  Acute Care Hospitals   
8     2053258100  Acute Care Hospitals   
9     2563864556  Acute Care Hospitals   
10    3347742601  Acute Care Hospitals   
11    2569275531  Acute Care Hospitals   
12    3342882100  Acute Care Hospitals   
13    3342938000  Acute Care Hospitals   
14    3347493411  Acute Care Hospitals   
15    2563572111  Acute Care Hospitals   
16    2059344011  Acute Care Hospitals   
17    3342836541  Acute Care Hospitals   
18    2567372000  Acute Care Hospitals   
19    3342228466  Acute Care Hospitals   

                             Hospital Ownership  ...  \
0   Government - Hospital District or Authority  ...   
1   Government - Hospital District or Authority  ...   
2   Government - Hospital District or Authority  ...   
3                Voluntary non-profit - Private  ...   
4                                   Proprietary  ...   
5                Voluntary non-profit - Private  ...   
6                 

In [2]:
df.isnull().sum()


Provider ID                                                         0
Hospital Name                                                       0
Address                                                             0
City                                                                0
State                                                               0
ZIP Code                                                            0
County Name                                                        15
Phone Number                                                        0
Hospital Type                                                       0
Hospital Ownership                                                  0
Emergency Services                                                  0
Meets criteria for meaningful use of EHRs                         143
Hospital overall rating                                             0
Hospital overall rating footnote                                 3414
Mortality national c

In [3]:
df.describe()

Provider ID      ZIP Code  Phone Number
count    4812.000000   4812.000000  4.812000e+03
mean   268294.422901  53990.132377  5.849100e+09
std    157109.340215  26915.916870  2.331563e+09
min     10001.000000    603.000000  9.369338e+08
25%    140185.750000  33015.250000  4.015615e+09
50%    260043.500000  55410.500000  6.053413e+09
75%    390222.250000  76035.500000  7.877574e+09
max    670118.000000  99929.000000  9.898943e+09

In [4]:
dropcolumn = list(df.filter(regex='footnote'))
df_clean = df[df.columns.drop(dropcolumn)]
df_clean.head()

Provider ID                     Hospital Name                     Address  \
0        10001  SOUTHEAST ALABAMA MEDICAL CENTER      1108 ROSS CLARK CIRCLE   
1        10005     MARSHALL MEDICAL CENTER SOUTH  2505 U S HIGHWAY 431 NORTH   
2        10006    ELIZA COFFEE MEMORIAL HOSPITAL          205 MARENGO STREET   
3        10007          MIZELL MEMORIAL HOSPITAL               702 N MAIN ST   
4        10008       CRENSHAW COMMUNITY HOSPITAL         101 HOSPITAL CIRCLE   

       City State  ZIP Code County Name  Phone Number         Hospital Type  \
0    DOTHAN    AL     36301     HOUSTON    3347938701  Acute Care Hospitals   
1      BOAZ    AL     35957    MARSHALL    2565938310  Acute Care Hospitals   
2  FLORENCE    AL     35631  LAUDERDALE    2567688400  Acute Care Hospitals   
3       OPP    AL     36467   COVINGTON    3344933541  Acute Care Hospitals   
4   LUVERNE    AL     36049    CRENSHAW    3343353374  Acute Care Hospitals   

                            Hospital Ownership Emergency Services  \
0  Government - Hospital District or Authority                Yes   
1  Government - Hospital District or Authority                Yes   
2  Government - Hospital District or Authority                Yes   
3               Voluntary non-profit - Private                Yes   
4                                  Proprietary                Yes   

  Meets criteria for meaningful use of EHRs Hospital overall rating  \
0                                         Y                       3   
1                                         Y                       3   
2                                         Y                       2   
3                                         Y                       2   
4                                         Y                       3   

  Mortality national comparison Safety of care national comparison  \
0  Same as the national average         Above the national average   
1    Below the national average       Same as the national average   
2    Below the national average       Same as the national average   
3  Same as the national average                      Not Available   
4  Same as the national average                      Not Available   

  Readmission national comparison Patient experience national comparison  \
0    Same as the national average             Below the national average   
1      Above the national average           Same as the national average   
2    Same as the national average             Below the national average   
3      Below the national average           Same as the national average   
4    Same as the national average                          Not Available   

  Effectiveness of care national comparison  \
0              Same as the national average   
1              Same as the national average   
2              Same as the national average   
3                Below the national average   
4              Same as the national average   

  Timeliness of care national comparison  \
0           Same as the national average   
1             Above the national average   
2             Above the national average   
3             Above the national average   
4             Above the national average   

  Efficient use of medical imaging national comparison  
0                       Same as the national average    
1                         Below the national average    
2                       Same as the national average    
3                                      Not Available    
4                                      Not Available

In [5]:
new_df= df_clean.replace('Not Available', np.nan )
new_df

Provider ID                     Hospital Name  \
0           10001  SOUTHEAST ALABAMA MEDICAL CENTER   
1           10005     MARSHALL MEDICAL CENTER SOUTH   
2           10006    ELIZA COFFEE MEMORIAL HOSPITAL   
3           10007          MIZELL MEMORIAL HOSPITAL   
4           10008       CRENSHAW COMMUNITY HOSPITAL   
...           ...                               ...   
4807       670118              FIRST TEXAS HOSPITAL   
4808       640001       LBJ TROPICAL MEDICAL CENTER   
4809       650001  GUAM MEMORIAL HOSPITAL AUTHORITY   
4810       650003        GUAM REGIONAL MEDICAL CITY   
4811       660001        COMMONWEALTH HEALTH CENTER   

                            Address       City State  ZIP Code County Name  \
0            1108 ROSS CLARK CIRCLE     DOTHAN    AL     36301     HOUSTON   
1        2505 U S HIGHWAY 431 NORTH       BOAZ    AL     35957    MARSHALL   
2                205 MARENGO STREET   FLORENCE    AL     35631  LAUDERDALE   
3                     702 N MAIN ST        OPP    AL     36467   COVINGTON   
4               101 HOSPITAL CIRCLE    LUVERNE    AL     36049    CRENSHAW   
...                             ...        ...   ...       ...         ...   
4807                9922 LOUETTA RD    HOUSTON    TX     77070      HARRIS   
4808                FAGAALU VILLAGE  PAGO PAGO    AS     96799         NaN   
4809  85O GOV CARLOS G CAMACHO ROAD   TAMUNING    GU     96913         NaN   
4810                    133 ROUTE 3     DEDEDO    GU     96929         NaN   
4811   PO BOX 409CK, NAVY HILL ROAD    GARAPAN    MP     96950         NaN   

      Phone Number         Hospital Type  \
0       3347938701  Acute Care Hospitals   
1       2565938310  Acute Care Hospitals   
2       2567688400  Acute Care Hospitals   
3       3344933541  Acute Care Hospitals   
4       3343353374  Acute Care Hospitals   
...            ...                   ...   
4807    8442641435  Acute Care Hospitals   
4808    6846334590  Acute Care Hospitals   
4809    6716472552  Acute Care Hospitals   
4810    6716455500  Acute Care Hospitals   
4811    6702348950  Acute Care Hospitals   

                               Hospital Ownership Emergency Services  \
0     Government - Hospital District or Authority                Yes   
1     Government - Hospital District or Authority                Yes   
2     Government - Hospital District or Authority                Yes   
3                  Voluntary non-profit - Private                Yes   
4                                     Proprietary                Yes   
...                                           ...                ...   
4807                                  Proprietary                Yes   
4808  Government - Hospital District or Authority                Yes   
4809                           Government - Local                Yes   
4810               Voluntary non-profit - Private                Yes   
4811                                  Proprietary                Yes   

     Meets criteria for meaningful use of EHRs Hospital overall rating  \
0                                            Y                       3   
1                                            Y                       3   
2                                            Y                       2   
3                                            Y                       2   
4                                            Y                       3   
...                                        ...                     ...   
4807                                       NaN                     NaN   
4808                                         Y                     NaN   
4809                                         Y                       3   
4810                                       NaN                     NaN   
4811                                         Y                     NaN   

     Mortality national comparison Safety of care national comparison  \
0     Same as the national average         Above the

In [6]:
#converting to numerial values
ordinal_col = list(new_df.filter(regex="national comparison"))

mapper = {
    'Below the national average' : 0,
    'Same as the national average' : 1, 
    'Above the national average' : 2
}
for col in ordinal_col:
    new_df.loc[:, new_df.columns == col]= new_df.loc[:, new_df.columns == col].replace(mapper)
new_df.head() 

Provider ID                     Hospital Name                     Address  \
0        10001  SOUTHEAST ALABAMA MEDICAL CENTER      1108 ROSS CLARK CIRCLE   
1        10005     MARSHALL MEDICAL CENTER SOUTH  2505 U S HIGHWAY 431 NORTH   
2        10006    ELIZA COFFEE MEMORIAL HOSPITAL          205 MARENGO STREET   
3        10007          MIZELL MEMORIAL HOSPITAL               702 N MAIN ST   
4        10008       CRENSHAW COMMUNITY HOSPITAL         101 HOSPITAL CIRCLE   

       City State  ZIP Code County Name  Phone Number         Hospital Type  \
0    DOTHAN    AL     36301     HOUSTON    3347938701  Acute Care Hospitals   
1      BOAZ    AL     35957    MARSHALL    2565938310  Acute Care Hospitals   
2  FLORENCE    AL     35631  LAUDERDALE    2567688400  Acute Care Hospitals   
3       OPP    AL     36467   COVINGTON    3344933541  Acute Care Hospitals   
4   LUVERNE    AL     36049    CRENSHAW    3343353374  Acute Care Hospitals   

                            Hospital Ownership Emergency Services  \
0  Government - Hospital District or Authority                Yes   
1  Government - Hospital District or Authority                Yes   
2  Government - Hospital District or Authority                Yes   
3               Voluntary non-profit - Private                Yes   
4                                  Proprietary                Yes   

  Meets criteria for meaningful use of EHRs Hospital overall rating  \
0                                         Y                       3   
1                                         Y                       3   
2                                         Y                       2   
3                                         Y                       2   
4                                         Y                       3   

   Mortality national comparison  Safety of care national comparison  \
0                            1.0                                 2.0   
1                            0.0                                 1.0   
2                            0.0                                 1.0   
3                            1.0                                 NaN   
4                            1.0                                 NaN   

   Readmission national comparison  Patient experience national comparison  \
0                              1.0                                     0.0   
1                              2.0                                     1.0   
2                              1.0                                     0.0   
3                              0.0                                     1.0   
4                              1.0                                     NaN   

   Effectiveness of care national comparison  \
0                                        1.0   
1                                        1.0   
2                                        1.0   
3                                        0.0   
4                                        1.0   

   Timeliness of care national comparison  \
0                                     1.0   
1                                     2.0   
2                                     2.0   
3                                     2.0   
4                                     2.0   

   Efficient use of medical imaging national comparison  
0                                                1.0     
1                                                0.0     
2                                                1.0     
3                                                NaN     
4                                                NaN

In [41]:
DF = new_df.dropna()


In [76]:
noduplicate = DF.drop_duplicates(['Provider ID','ZIP Code'])
utility_value = DF.pivot_table(values='Hospital overall rating', index='ZIP Code', columns='Provider ID', aggfunc='first',fill_value=0)
utility_value.head()

Provider ID 10001  10005  10006  10011  10012  10016  10019  10021  10023   \
ZIP Code                                                                     
1040             0      0      0      0      0      0      0      0      0   
1060             0      0      0      0      0      0      0      0      0   
1085             0      0      0      0      0      0      0      0      0   
1104             0      0      0      0      0      0      0      0      0   
1199             0      0      0      0      0      0      0      0      0   

Provider ID 10024   ... 670047 670055 670056 670060 670068 670077 670079  \
ZIP Code            ...                                                    
1040             0  ...      0      0      0      0      0      0      0   
1060             0  ...      0      0      0      0      0      0      0   
1085             0  ...      0      0      0      0      0      0      0   
1104             0  ...      0      0      0      0      0      0      0   
1199             0  ...      0      0      0      0      0      0      0   

Provider ID 670080 670082 670088  
ZIP Code                          
1040             0      0      0  
1060             0      0      0  
1085             0      0      0  
1104             0      0      0  
1199             0      0      0  

[5 rows x 2297 columns]

In [77]:
utility_value.shape

(2172, 2297)

In [78]:
X1 = utility_value.T
X1.head()

ZIP Code    1040  1060  1085  1104  1199  1201  1301  1432  1440  1453   ...  \
Provider ID                                                              ...   
10001           0     0     0     0     0     0     0     0     0     0  ...   
10005           0     0     0     0     0     0     0     0     0     0  ...   
10006           0     0     0     0     0     0     0     0     0     0  ...   
10011           0     0     0     0     0     0     0     0     0     0  ...   
10012           0     0     0     0     0     0     0     0     0     0  ...   

ZIP Code    99204 99208 99210 99216 99336 99352 99362 99508 99645 99701  
Provider ID                                                              
10001           0     0     0     0     0     0     0     0     0     0  
10005           0     0     0     0     0     0     0     0     0     0  
10006           0     0     0     0     0     0     0     0     0     0  
10011           0     0     0     0     0     0     0     0     0     0  
10012           0     0     0     0     0     0     0     0     0     0  

[5 rows x 2172 columns]

In [79]:
X1.shape

(2297, 2172)

In [80]:
X=X1

In [81]:
#converting to truncated SVD
import sklearn
from sklearn.decomposition import TruncatedSVD

SVD = TruncatedSVD(n_components=10)

# model fitting
decomposed_matrix = SVD.fit_transform(X1)
decomposed_matrix.shape

(2297, 10)

In [82]:
correlation_matrix = np.corrcoef(decomposed_matrix)
correlation_matrix.shape

(2297, 2297)

In [83]:
X1.index[60]

30016

In [84]:
i = 30016

provider_id = list(X1.index)
provider_id

    

[10001,
 10005,
 10006,
 10011,
 10012,
 10016,
 10019,
 10021,
 10023,
 10024,
 10029,
 10033,
 10035,
 10036,
 10038,
 10039,
 10040,
 10046,
 10049,
 10055,
 10056,
 10061,
 10065,
 10078,
 10079,
 10083,
 10085,
 10086,
 10087,
 10089,
 10090,
 10092,
 10100,
 10103,
 10104,
 10108,
 10113,
 10114,
 10118,
 10126,
 10130,
 10131,
 10139,
 10144,
 10149,
 10150,
 10157,
 10158,
 10164,
 20001,
 20006,
 20012,
 30002,
 30006,
 30007,
 30010,
 30011,
 30012,
 30013,
 30014,
 30016,
 30023,
 30024,
 30033,
 30036,
 30038,
 30043,
 30055,
 30061,
 30062,
 30064,
 30065,
 30068,
 30069,
 30085,
 30087,
 30088,
 30089,
 30092,
 30093,
 30101,
 30103,
 30110,
 30111,
 30114,
 30115,
 30117,
 30119,
 30121,
 30122,
 30123,
 40004,
 40007,
 40010,
 40014,
 40016,
 40017,
 40020,
 40022,
 40026,
 40027,
 40029,
 40036,
 40039,
 40041,
 40050,
 40051,
 40055,
 40062,
 40067,
 40071,
 40078,
 40084,
 40088,
 40114,
 40118,
 40119,
 40134,
 50002,
 50006,
 50007,
 50009,
 50013,
 50014,
 50017,


In [85]:
indexs= provider_id.index(i)
indexs

60

In [86]:
correlation_provider_id = correlation_matrix[indexs]
correlation_provider_id.shape

(2297,)

In [87]:
#recommending n from the list
Recommend = list(X.index[correlation_provider_id > 0.90])
 

a = Recommend[0:5]
a

[30016]

In [88]:
#splitting train and test data to find accuracy value
x=DF.loc[:,['Hospital overall rating']]
x
y=x[:20000]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4,random_state=100)


In [89]:
#using SVC classifier
from sklearn.svm import SVC
from sklearn import metrics
svc=SVC() 
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
#Accuracy value
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred))

Accuracy Score:
1.0


C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [90]:
#converting to float value
from sklearn.model_selection import train_test_split
y = pd.to_numeric(DF['Hospital overall rating'], downcast='float')
y.values
providerId = pd.to_numeric(DF['Provider ID'], downcast='float')
providerId


0        10001.0
1        10005.0
2        10006.0
5        10011.0
6        10012.0
          ...   
4776    670077.0
4778    670079.0
4779    670080.0
4780    670082.0
4784    670088.0
Name: Provider ID, Length: 2297, dtype: float32

In [91]:
#splitting the dataset
import sklearn.model_selection as model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(providerId, y, test_size=0.4,random_state=109)


In [92]:
#reshape the feature extracted
X_train = X_train.values
X = X_train.reshape(-1, 1)
X_test = X_test.values
y_train = y_train.values
y = y_train.reshape(-1, 1)
y_test = y_test.values

In [93]:
#importing 
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, recall_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB
import collections

In [94]:
classifiers = {
    "Support Vector Classifier": SVC()
}

In [95]:
#Determining accuracy
from sklearn.model_selection import cross_val_score
for key, classifier in classifiers.items():
    classifier.fit(X , y)
    acc_score = cross_val_score(classifier, X, y, cv=5)
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score of", round(acc_score.mean(), 2), "accuracy score")
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score percentage of", round(acc_score.mean(), 2) * 100, " % accuracy percentage")

C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

Classifiers:  SVC Has a accuracy score of 0.45 accuracy score
Classifiers:  SVC Has a accuracy score percentage of 45.0  % accuracy percentage


C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [96]:
#knn

In [100]:
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
knn = np.array(utility_value.values)
knn.size
nbrs = NearestNeighbors(n_neighbors=3, algorithm='ball_tree').fit(knn)
distances, indices = nbrs.kneighbors(knn)


In [101]:
print(indices)

[[   0  120   12]
 [   1  120   12]
 [   2  120   12]
 ...
 [2169   12  120]
 [2170   12  120]
 [2171  120   12]]


In [103]:
classifiers = {
     "KNearest": KNeighborsClassifier()
}

In [104]:
#accuracy value with knearest classifier
from sklearn.model_selection import cross_val_score
for key, classifier in classifiers.items():
    classifier.fit(X , y)
    acc_score = cross_val_score(classifier, X, y, cv=5)
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score of", round(acc_score.mean(), 2), "accuracy score")
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score percentage of", round(acc_score.mean(), 2) * 100, " % accuracy percentage")

Classifiers:  KNeighborsClassifier Has a accuracy score of 0.4 accuracy score
Classifiers:  KNeighborsClassifier Has a accuracy score percentage of 40.0  % accuracy percentage


C:\Users\varsh\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A 